### PR TITLE
Allow arbitrary server configuration before/after custom LDIF files load

### PR DESCRIPTION
**Pull request by cfryanr**
**Description of the change**

We use this excellent container image in our integration tests for our open source project https://github.com/vmware-tanzu/pinniped

We wanted to be able to further configure our openldap server to use the `memberOf` overlay and to require that clients connect using TLS/StartTLS. I couldn't figure out a way to accomplish either of these objectives with bitnami/bitnami-docker-openldap, hence this PR to make both possible. You already offer `$LDAP_CUSTOM_LDIF_DIR` to execute arbitrary LDIF, but those files are loaded by the admin user, and that user does not seem to have permission to reconfigure the server.

New features added in the PR:
- Optionally load LDIF files to configure the server before the custom LDIF files are loaded as the admin user. This allows configuring things which need to exist before users and groups are created, such as the `memberOf` overlay. This is controlled by the new `$LDAP_SERVER_CONFIG_BEFORE_CUSTOM_LDIF_DIR` env var.
- Also optionally load other LDIF files to configure the server after the custom LDIF files are loaded as the admin user. This allows configuring things which need to happen after the users and groups are created, such as disabling all non-TLS client connections, which needs to happen after the users/groups are created or else the connection used to create them will be rejected for not using TLS. This is controlled by the new `$LDAP_SERVER_CONFIG_AFTER_CUSTOM_LDIF_DIR` env var.

You can see how we are planning to use these features in this example deployment, which is how we deploy openldap for our integration tests: https://github.com/vmware-tanzu/pinniped/blob/ldap_starttls/test/deploy/tools/ldap.yaml

I am not an openldap expert, so its entirely possible that there may be a better way to accomplish these outcomes. I would love to hear your feedback.

**Benefits**

Ability to further configure the openldap server.

**Possible drawbacks**

Maybe too many configuration options. :)

**Applicable issues**

These seem related: #22 #30 #17 

**Additional information**

Thanks for considering this PR!

### CODE REVIEW

**Comment by migruiz4** [comment]
Hi @cfryanr,

Thank you very much! I really appreciate the contribution and the detailed description.

Your PR looks good to me, but we'd like to check if there is a different alternative to adding `_BEFORE`/`_AFTER` hooks.

It is not necessarily a bad thing, but I'm worried that in the future other use cases could require other hooks so we would end up with something like `_BEFORE_BEFORE` and `_AFTER_AFTER`.

If you don't mind, I'd like to dedicate some time to look if there is any alternative before approving and merging this PR.

I will get back to you as soon as possible.

**Comment by cfryanr** [comment]
@migruiz4 Absolutely, thanks for looking at it.

I copied your pattern of running all the `*.ldif` files in the directory in sorted order, so hopefully that would prevent needing any `_BEFORE_BEFORE` or `_AFTER_AFTER`, since you can always add more files to those directories and control the order in which they are executed. That being said, I don't really have any opinion on how to implement the hooks... I just needed any way to accomplish the outcomes that I outlined above.

**Comment by rafariossaa** [comment]
Hi @cfryanr,
  Could I have an example of the ldiff files you are trying to load ?. I would like to check the permissions needed by the adminuser.
  Also,  the container currently provides `LDAP_CUSTOM_SCHEMA_FILE` so you can load a custom schema. That is done [here](https://github.com/bitnami/bitnami-docker-openldap/blob/cd8f316ba455b49547568d051b88b4ce391f3533/2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh#L414) and maybe this works for your use case. 
  What do you think ? Could you give it a try ?

**Comment by cfryanr** [comment]
Hi @rafariossaa, thanks for looking at the PR.

More specific versions of the link above with the LDIF files that I'm trying to load:
- This is the file in the `LDAP_CUSTOM_LDIF_DIR` to create orgs and users and groups: https://github.com/vmware-tanzu/pinniped/blob/ldap_starttls/test/deploy/tools/ldap.yaml#L11-L118
- This is the file that I would like to load before that to enable the members overlay: https://github.com/vmware-tanzu/pinniped/blob/ldap_starttls/test/deploy/tools/ldap.yaml#L138-L171
- And this is the file that I would like to load after that to disable non-TLS client connections: https://github.com/vmware-tanzu/pinniped/blob/ldap_starttls/test/deploy/tools/ldap.yaml#L181-L185

I just tried the `LDAP_CUSTOM_SCHEMA_FILE` for activating the memberOf overlay and it seemed to work! I'm not sure if it would have worked for any arbitrary LDIF commands, but it seemed to work for the specific commands that I was trying to run. The `slapadd -n 0` command used by `LDAP_CUSTOM_SCHEMA_FILE` seems to operate on a different context than the `ldapadd` commands used for the other env var settings.

However, when I tried to also add the lines to disable non-TLS to the `LDAP_CUSTOM_SCHEMA_FILE` it gave me a parse error, even though those exact same lines work with `LDAP_SERVER_CONFIG_AFTER_CUSTOM_LDIF_DIR`. It seems like it doesn't allow `changetype: modify` in that context. Even if it had worked, I think it would have prevented the `LDAP_CUSTOM_LDIF_DIR` which comes next from working since that does not use TLS, because that's what happens when I disable non-TLS in `LDAP_SERVER_CONFIG_BEFORE_CUSTOM_LDIF_DIR`.

Any suggestions?

**Comment by rafariossaa** [comment]
Hi,
  Thanks for the feedback.
  I can see that there could be too many combinations for settings to cover them all in an easy way.
  There is other approach to tackle this requirement I would like to share with you.
  In our mysql container, we use what are called  `custom init scripts`. This way, the user can provide some shell scripts and perform the actions needed. 
  You can see the code [here](https://github.com/bitnami/bitnami-docker-mysql/blob/ca962e7f128805c13a16b2e25705c71dc0935179/8.0/debian-10/rootfs/opt/bitnami/scripts/libmysql.sh#L333), and the call [here](https://github.com/bitnami/bitnami-docker-mysql/blob/ca962e7f128805c13a16b2e25705c71dc0935179/8.0/debian-10/rootfs/opt/bitnami/scripts/mysql/setup.sh#L33).
  Do you think this approach would be better for this kind of use case ?

**Comment by rafariossaa** [comment]
Hi,
> Allowing arbitrary shell scripts could be quite flexible indeed. I suppose they could load the same bash helper functions from /opt/bitnami/scripts and have access to the same env vars.

Yes, you can do whatever is needed in the shell scripts.

> How would it interact with the ldap_initialize() function though, which effectively defines the order of initialization steps and is not currently customizable? Perhaps something that makes this whole block of code customizable/overwritable in a provided custom shell script? Curious what you had in mind?

I think that the logic could be something like, if there are **not** custom scripts go with the current logic, if there are custom scripts then run them (as in the mysql code).

> Another option to consider might be to just create a new configuration option $REQUIRE_TLS=yes/no to solve the specific use case. 
Maybe yes for this case, but if other settings are needed I would vote for custom init scripts. There are a hundreds for openldap settings and combinations that would require lots of parameters and complex logic to handle the combinations.

**Comment by cfryanr** [comment]
One downside of completely replacing the `ldap_initialize()` function with custom code would be that the user has essentially forked the repo at that point (not literally forked, but has the same downsides). Any upstream changes to the `ldap_initialize()` function would need to be reflected into the user's logic or else the functionality of each configuration environment variable could be broken, making it unsafe for the user to always pull `latest` of the container image. Of course, the advantage would be ultimate flexibility, but at this cost.

Perhaps it would be safer to break up the `ldap_initialize()` function into more steps, and then allow the user to add their own custom steps in between each step? That way they would never need to replace the whole thing. Not sure.

I don't think the LDAP_SERVER_CONFIG_AFTER_CUSTOM_LDIF_DIR (or LDAP_CUSTOM_SCHEMA_FILE) and LDAP_SERVER_CONFIG_AFTER_CUSTOM_LDIF_DIR approach has this same downside. Those, or something similar, are extension points for which it should be fairly easy to maintain backwards compatibility, and therefore fairly safe for the user to upgrade to newer versions.

Happy to go with whatever the project maintainers decide. Like I said before, I'm just looking to handle some specific use cases. :)

**Comment by rafariossaa** [comment]
Hi,
  We are having some internal discussion for the best approach for this.
  I will come back as soon as possible.

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the long delay.
  Due to the complexity of handling the use cases,  I think that for this I would for a all-or-nothing behavior. 
  I mean, leave the current initialization procedure where you can pass some environment variables to set some values, or if you need something different then do whatever is needed in a provided init-scripts.
  I think this approach would be better than ending with a bunch of hooks that maybe is not what you really need in a certain point or for a certain configuration.
  What do you think ?.

**Comment by cfryanr** [comment]
Thanks, @rafariossaa.

As a user, my preference would be for any solution that allows me to get my job done without effectively forking the container's initialization code. Once I need to effectively fork the code, then it is actually easier for me to literally fork the GitHub repository and maintain my own fork, because at least that will assist me in pulling/merging upstream changes.

Since `LDAP_CUSTOM_SCHEMA_FILE` works for activating the memberOf overlay (thanks for pointing that out!) then I really just need some way to disable non-TLS connections.

Disabling non-TLS connections could be accomplished lots of ways... with generic hooks, with a specific configuration env var, or something else. But ideally it would be some way that makes upgrading to new releases of of official `bitnami-docker-openldap` published container images seamless for users who have disabled non-TLS connections, without the user needing to manually analyze the underlying initialization source code during each upgrade to decide if they have overridden the source in such a way that used to avoid breaking the other configuration options but is perhaps no longer safe/effective.  :)

**Comment by rafariossaa** [comment]
Hi,
  In the case of an container upgrade, you only will need to remove the initscripts and keep the volume where data is stored, the [current logic](https://github.com/bitnami/bitnami-docker-openldap/blob/8539f63e968fa9d65d04224d3cc9804f24429574/2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh#L413) will detect the data and start with it.
  Would this work for you ?

**Pull request closed without merging**
