### PR TITLE
Add configuration for disabling anonymous bindings

### PR DESCRIPTION
**Pull request by danifalcon**
**Description of the change**
Add the environment config variable LDAP_ALLOW_ANON_BINDING to provide a possibility to disable anonymous bindings to the OpenLDAP server. The default value it's yes, so if you just don't want to disable the anonymous bindings you don't need to do any change.

**How to use it**
The new config its really easy to use , just like the already existing configurations, just need to provide the environment variable in the docker-compose.yml file as the following example:

Captura de pantalla 2021-07-08 a las 15 20 51

### CODE REVIEW

**Review by rafariossaa — CHANGES_REQUESTED** [review]
Hi,
 Thanks for adding this, the code LGTM but could you add this new enviroment variable to the REAMDE with a short description.  That would be useful for other users.

**Comment by danifalcon** [comment]
Hi,
Requested changes were added.
Thanks for your review @rafariossaa

**Review by rafariossaa — APPROVED** [review]
LGTM

**Comment by rafariossaa** [comment]
Note:
Our CI/CD system needs some time to build and publish a new image version with these changes. Usually this should happen in one or two day.

**Comment by danifalcon** [comment]
Why the changes implemented in this branch was removed by the bitnami-bot? https://github.com/bitnami/bitnami-docker-openldap/commit/6924f5bfef4aa1bef3fc98de0124059c206ba7a6

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, it seems we had some issues in the pipeline when publishing the changes.
  I fixed it and release a new version with you changes.
  Sorry for the noise.

**Pull request merged**
