### PR TITLE
(alternative approach) make LDAP_SKIP_DEFAULT_TREE only skip generation of default tree, not schema or LDIF import

### LINKED ISSUE #86: Split generation of default tree from setting up schemas (and extra schemas) and importing of LDIF files
### Name and Version

bitnami/openldap:2.5.11

### What steps will reproduce the bug?

Setting the variable `LDAP_SKIP_DEFAULT_TREE` will skip creation of the "content" of the LDAP tree, like users and such.

But it will also skip adding schemas to the configuration, as well as importing LDIF files:
https://github.com/bitnami/bitnami-docker-openldap/blob/master/2.5/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh#L466
```
        if is_boolean_yes "$LDAP_SKIP_DEFAULT_TREE"; then
            info "Skipping default schemas/tree structure"
        else
            # Initialize OpenLDAP with schemas/tree structure
            ldap_add_schemas
            if [[ -f "$LDAP_CUSTOM_SCHEMA_FILE" ]]; then
                ldap_add_custom_schema
            fi
```

From what I understood in #83 the automatic import cannot modify things under `cn=config`, so adding the schemas to the `LDAP_CUSTOM_LDIF_DIR` directory will not work.

I think the logic should be:
```
        # Initialize OpenLDAP with schemas/tree structure
        ldap_add_schemas
        if [[ -f "$LDAP_CUSTOM_SCHEMA_FILE" ]]; then
            ldap_add_custom_schema
        fi
        if is_boolean_yes "$LDAP_SKIP_DEFAULT_TREE"; then
            info "Skipping default schemas/tree structure"
        else
                ldap_create_tree
        fi
        if ! is_dir_empty "$LDAP_CUSTOM_LDIF_DIR"; then
            ldap_add_custom_ldifs
        fi
```

### What is the expected behavior?

From the documentation:
```
LDAP_SKIP_DEFAULT_TREE: Whether to skip creating the default LDAP tree based on LDAP_USERS, LDAP_PASSWORDS, LDAP_USER_DC and LDAP_GROUP. Default: no
```
I would argue that this should **ONLY** skip the actual creation of the default tree. And nothing else. So it **should** create/add schemas and import LDIF objects.

(As all of the mentioned variables like `LDAP_USERS` have default values, it makes sense to only skip creation of LDAP entries from those variables. But still have schemas and import LDIFs...)

### What do you see instead?

Setting `LDAP_CUSTOM_SCHEMA_FILE` skips creation of default tree from attributes, addition of schemas, addition of custom schemas and importing of LDIF files.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by johanneskastl**
## split generation/addition of schemas and importing of LDIF files from generation of default LDAP tree when LDAP_SKIP_DEFAULT_TREE is set to yes

Also introduces a new variable `LDAP_ADD_SCHEMAS` (Default: yes) to let the user decide if schemas from `LDAP_EXTRA_SCHEMAS` should be added.

**Description of the change**

Make LDAP_SKIP_DEFAULT_TREE do what the README says:
```
LDAP_SKIP_DEFAULT_TREE: Whether to skip creating the default LDAP tree based on LDAP_USERS, LDAP_PASSWORDS, LDAP_USER_DC and LDAP_GROUP. Default: no
```
So if this is set to yes, schemas are added and custom schemas or LDIF files are being imported.

**Benefits**

You can skip only the generation of the default tree, but still get the schemas and you can import LDIF files.

**Possible drawbacks**

Changes existing behaviour, but as discussed with @fmulero this might be the least intrusive way to do so.

**Applicable issues**

Fixes #86 (and #/83)

### CODE REVIEW

**Review by miguelaeh — COMMENTED** [review]
Thanks for the PR!
I guess this change removes the ability of not executing `ldap_add_schemas`. Would it make sense to add a new env var to support it?

**Comment by johanneskastl** [comment]
> I guess this change removes the ability of not executing `ldap_add_schemas`. Would it make sense to add a new env var to support it?

I personally think that having environment variables to skip the steps individually would be a good addition. Importing the schemas, importing custom schemas, importing custom LDIF files, creating the default tree, ...

I did not want to clutter up the PR, but if you want I can add a proposal.

**Comment by johanneskastl** [comment]
Hi @miguelaeh @rafariossaa,

I extended the PR and added a new variable `LDAP_ADD_SCHEMAS` with default values of `yes`. If this is true, we add the schemas (the ones in the `LDAP_EXTRA_SCHEMAS` variable).

I do not know if you would like to have another variable for enabling/disabling the addition of custom schemas and maybe also custom LDIF files?

**Comment by miguelaeh** [comment]
I think it is better now, we can reach the same behaviour as before.
Let's wait for @rafariossaa thoughts since he is more experienced in LDAP

**Comment by johanneskastl** [comment]
@miguelaeh  @rafariossaa  Any objections to merging?

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the delay. I think it is good now. 
  Regarding the adding of new environments vars, I would wait for some other users having that scenario.
  Thanks .

**Review by rafariossaa — APPROVED** [review]
LGTM

**Pull request merged**
