### PR TITLE
Enable admin user for cn=config

### PR DESCRIPTION
**Pull request by habalux**
**Description of the change**

Hello! I was trying to deploy the image and configure some options via Ansible but noticed that the image seems to lack a default admin user for the `cn=config` tree. This is not accessible by the normal admin, so I decided to add support for a config admin user in the libopenldap.sh script.

The user is only created during initialization and only if `LDAP_CONFIG_ADMIN_ENABLED` is set to "yes". Username and password can be changed via `LDAP_CONFIG_ADMIN_USERNAME` and `LDAP_CONFIG_ADMIN_PASSWORD.` Resulting user DN is `cn=<username>,cn=config`.

**Benefits**

Allows `cn=config` to be managed via non-local connection.

**Possible drawbacks**

Shouldn't be any by default, the user is only enabled when explicitly specified.

**Applicable issues**

**Additional information**

### CODE REVIEW

**Review by juan131 — COMMENTED** [review]
Hi @habalux 

Thanks so much for this contribution!! I'd like @rafariossaa to take a look since he has more experience with LDAP trees than me.

That said, I have one question: why not reusing the same admin user/password credentials to create the admin user for `cn=config`?

**Comment by rafariossaa** [comment]
Hi @habalux,
  In the code, we are currently [creating and admin user](https://github.com/bitnami/bitnami-docker-openldap/blob/045482dfd0d56e6a018b929a56286bc0208a2693/2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh#L234), but is its created in `dn: olcDatabase={2}hdb,cn=config`. Instead of creating a new admin in `dn: olcDatabase={0}config,cn=config`, maybe it would be better to create replace [those lines in the code](https://github.com/bitnami/bitnami-docker-openldap/blob/045482dfd0d56e6a018b929a56286bc0208a2693/2/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh#L237).
  What do you  think ?.

**Comment by habalux** [comment]
@juan131 @rafariossaa Thanks for the feedback! I consider the regular admin to be reserved for regular (data related) management. The config admin has a lot more power over the server configuration (like ACLs) so I think it should be a separate account with its own password. Also doing it this way won't accidentally break/compromise any existing setups or deployment pipelines.

**Comment by juan131** [comment]
I don't like the idea of having two admin users. IMHO the admin user should have permissions to manage everything (both data and configuration).

That said, I'm not an expert on LDAP and I don't know what's the most common approach to deal with this.

**Comment by habalux** [comment]
Having a separate config admin seems to be pretty normal in with OpenLDAP at least. The Osixia image includes this for example, as well as do numerous tutorials it seems.

So security wise I'd say it's better to separate but obviously there are other preferences too. I could modify the script further so that the regular admin would be allowed to manage the config by default, but it could also allow a separate admin user if required. And of course it would still be required to explicitly enable the extra initialization bits altogether so there are no breaking changes. How does this sound?

**Comment by juan131** [comment]
Hi @habalux 

Thanks so much again for providing the context.

My colleague @rafariossaa is analyzing pros and cons of using two admin vs a single admin with privileges on both data and configuration. He's double-checking with other OpenLDAP admins about their preferences and common use cases. We'll get back to you soon with more details.

**Comment by heinebold** [comment]
Do I understand this correctly, that this change would give us a way to configure ACLs and overlays without the changes proposed in #34 ?

**Comment by juan131** [comment]
Hi @heinebold 

This contribution allows you to define a separate config admin. Defining custom ACL(s) is out of the scope of this contribution.

**Comment by heinebold** [comment]
Yeah I know it doesn't affect ACLs per se, I was just thinking that the here mentioned admin user might at least provide us with the means to edit them.

Is there a chance you're going to approve any kind of contribution that gives us a chance to actually configure the thing? You don't really like this one, you didn't like the other PR I mentioned. All we need is a fesaible way to touch the configuration...

**Comment by juan131** [comment]
Hi @heinebold 

It's very likely that we go ahead with the approach, my colleague @rafariossaa was analyzing pros and cons regarding having two admins (AFAIK he agreed with this) and he was also exploring the possibility to deprecate the `hdb` database in favor or the `mdb` one (and find an upgrade path).

Please note that sometimes this investigations get delayed due to other priorities. In any case, I'll ping him so he can give us an update.

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the delay.
  I think that yes, we can have an admin for the configuration and other admin for the data. :+1:

**Comment by habalux** [comment]
@rafariossaa great, thanks 👍 

I rebased my branch to remove some newly occurred conflicts, now it's ready to merge again.

**Review by juan131 — APPROVED** [review]
LGTM

**Comment by juan131** [comment]
Hi @habalux 

Thanks again for this great contribution! Two new images including your changes were just release: `2.4.59-debian-10-r26` and `2.5.6-debian-10-r15`.

Please give them a try to confirm everything works as expected when possible.

**Comment by habalux** [comment]
Hi @juan131 

I tested the images and found that some newline changes made by bitnami-bot caused invalid ldif to be generated. I created #50 to fix the issue.

**Comment by juan131** [comment]
Thanks for the fix @habalux ! Landed and available at image versions `2.4.59-debian-10-r27` and `2.5.6-debian-10-r16`.

**Pull request merged**
